apiVersion: v1
kind: Service
metadata:
  name: sts-service
spec:
  selector:
    app: my-app
  ports:
    - name: k21-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-statefulset
spec:
  serviceName: sts-service
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: 11905510/k21academy:1.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /var/www/html
        - name: mysql-container
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: nginx-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path  #Replace with your storageclass name
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path  #Replace with your storageclass name
        resources:
          requests:
            storage: 2Gi


